[package]
name = "egui_graph"
version = "0.1.0"
license = "MIT"
homepage = "https://github.com/blitzarx1/egui_graph"
repository = "https://github.com/blitzarx1/egui_graph"
edition = "2021"

[dependencies]
egui = "0.21.0"
petgraph = "0.6"
fdg-sim = "0.9.1"

[workspace]
resolver = "2"
members = ["examples/*"]
