[package]
name = "egui_graph"
version = "0.0.1"
authors = ["Dmitrii Samsonov <blitzarx1@gmail.com>"]
license = "MIT"
homepage = "https://github.com/blitzarx1/egui_graph"
repository = "https://github.com/blitzarx1/egui_graph"
description = "Graph visualisation for egui"
edition = "2021"

[dependencies]
egui = "0.21.0"
petgraph = "0.6"
fdg-sim = "0.9.1"

[workspace]
members = ["example"]
